/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  0.0

/rat/db/set DETECTOR experiment "Watchman"
#/rat/db/set DETECTOR geo_file "Watchman/Watchman.geo"
/rat/db/set DETECTOR detector_factory "Watchman"

/run/initialize

# BEGIN EVENT LOOP
/rat/proc lesssimpledaq
/rat/proc fitbonsai
/rat/proc fitcentroid
/rat/proc fitpath
/rat/proc count
/rat/procset update 100

# Use IO.default_output_filename
/rat/proclast outroot
/rat/procset file "watchman_fastneutron_lesssimpledaq.root"
#END EVENT LOOP



/generator/add combo fastneutron:regexfill
/generator/pos/set rock_[0-9]+
/generator/vtx/set 0 0 0
/generator/fastneutron/depth 600.0
/generator/fastneutron/enthresh 10.0
/generator/fastneutron/sidewalls 1.0


/run/beamOn 10000

