#Set the detector parameters
/rat/db/set DETECTOR experiment "Watchman"
/rat/db/set DETECTOR geo_file "Watchman/Watchman.geo"

/run/initialize
/process/activate Cerenkov

# BEGIN EVENT LOOP
/rat/proc simpledaq
#/rat/proc fitbonsai
/rat/proc count
/rat/procset update 10

/rat/proclast outroot
/rat/procset file "watchman1.root"
#END EVENT LOOP

/generator/add combo reactor_es:fill
/generator/vtx/set 0.0000 0.0000 1.0000
/generator/pos/set 0 0 0
/generator/reactor_es/U235 0.4960
/generator/reactor_es/U238 0.0870
/generator/reactor_es/Pu239 0.3510
/generator/reactor_es/Pu241 0.0660

/run/beamOn 1853
